home/urls.py
from django.urls import path
from home import views

app_name = 'pizza'
urlpatterns = [
    path('', views.home, name='home'),
    path('add_pizza/', views.add_pizza, name='add_pizza'),
    path('search/', views.search, name='search'),
]

pizza/urls.py
from django.urls import path
from pizza import views

app_name = 'pizza'
urlpatterns = [
    path('', views.list_pizza, name='list_pizza'),
]

pizzashop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pizza/', include('pizza.urls', namespace='pizza')),
    path('', include('home.urls', namespace='home')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

pizza/models.py
from django.db import models

from helpers.choices import DoughTypeChoices
from helpers.upload_files import upload_pizza_image


# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'


class Pizza(models.Model):

    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='pizza')
    name = models.CharField(max_length=255)
    dough_type = models.CharField(max_length=10, choices=DoughTypeChoices.choices)
    description = models.TextField()
    image = models.ImageField(upload_to=upload_pizza_image)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

home/forms.py
from django import forms
from pizza.models import Pizza


class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ('name', 'dough_type', 'company', 'image')


class SearchForm(forms.Form):
    search_query = forms.CharField(max_length=150, label='Search for pizzas')

home/views.py
from django.shortcuts import render, redirect
from pizza.models import Pizza
from .forms import PizzaForm, SearchForm


def home(request):
    pizza_list = Pizza.objects.all()
    return render(request, 'home/index.html', {'pizza_list': pizza_list})


def add_pizza(request):
    forms = PizzaForm(request.POST, request.FILES)
    if forms.is_valid():
        print(forms.cleaned_data)
        forms.save()
        return redirect('home:home')
    return render(request, 'home/add_pizza.html', context={'forms': forms})


def search(request):
    pizzas = []
    form = SearchForm(request.GET)
    if form.is_valid():
        search_query = form.cleaned_data['search_query']
        pizzas = Pizza.objects.filter(name__icontains=search_query)
    return render(request, 'home/search.html', context={'form': form, 'pizzas': pizzas})

pizza/views.py
from django.shortcuts import render

# Create your views here.


def list_pizza(request):
    return render(request, 'pizza/pizza_list.html')

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>PIZZASHOP</title>
</head>

<body>
<div class='dashboard'>
    <div class="dashboard-nav">
        <header><a href="#!" class="menu-toggle"><i class="fas fa-bars"></i></a><a href="#"
                                                                                   class="brand-logo"><i
                class="fas fa-anchor"></i> <span>PIZZASHOP</span></a></header>
        <nav class="dashboard-nav-list"><a href="{% url 'home:home' %}" class="dashboard-nav-item"><i
                class="fas fa-home"></i>Home </a>
            <a href="{% url 'home:add_pizza' %}" class="dashboard-nav-item"><i class="fas fa-home"></i>Add Pizza</a>
            <a href="#" class="dashboard-nav-item active"><i class="fas fa-tachometer-alt"></i> All Pizzas
            </a>
            <div class='dashboard-nav-dropdown'><a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle"><i
                    class="fas fa-photo-video"></i> Media </a>
                <div class='dashboard-nav-dropdown-menu'><a href="#"
                                                            class="dashboard-nav-dropdown-item">All</a><a
                        href="#" class="dashboard-nav-dropdown-item">Recent</a><a
                        href="#" class="dashboard-nav-dropdown-item">Images</a><a
                        href="#" class="dashboard-nav-dropdown-item">Video</a></div>
            </div>
            <a href="#" class="dashboard-nav-item"><i class="fas fa-cogs"></i> Settings </a><a
                    href="#" class="dashboard-nav-item"><i class="fas fa-user"></i> Profile </a>
            <div class="nav-item-divider"></div>
            <a
                    href="#" class="dashboard-nav-item"><i class="fas fa-sign-out-alt"></i> Login </a>
        </nav>
    </div>
    <div class='dashboard-app'>
        <header class='dashboard-toolbar'><a href="#!" class="menu-toggle"><i class="fas fa-bars"></i></a></header>

        {% block content %}

        {% endblock %}

    </div>


</div>


</body>

<script src="{% static 'js/main.js' %}"></script>
</html>

templates/home/add_pizza.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ forms.as_p }}
    <input type="submit" value="OK">
    </form>
{% endblock %}

templates/home/index.html
{% extends 'base.html' %}

{% block content %}
      <h1>Search Pizzas</h1>

        <form action="{% url 'home:search' %}" method="GET">
            <input type="text" name="search_query" placeholder="Search for pizzas">
            <input type="submit" value="Search">
        </form>

    <div class='card'>
        <div class='card-header'>
            <h1>Pizza Shop market</h1>
        </div>
        <div class='card-body'>
            <p>We are happy that you are with us, we are offering blya blya blya</p>
        </div>
    </div>
    <div class="container">
        <div class="card-group">
            {% for pizza in pizza_list %}
                <div class="card" style="width:400px">
                    <img src="{{ pizza.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ pizza.name }}</h5>
                        <p class="card-text">{{ pizza.description }}
                            </p>

                            <button type="button" class="btn btn-primary">Detail page</button>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/home/search.html
{% extends 'base.html' %}

{% block content %}
    {% if pizzas %}
        <ul>
            {% for pizza in pizzas %}
                <li>{{ pizza.name }}</li>
                <li>{{ pizza.company.name }}</li>
                <img src="{{ pizza.image.url }}" class="card-img-top" alt="...">
            {% endfor %}
        </ul>
    {% else %}
        <p>No pizzas found</p>
    {% endif %}
{% endblock %}

templates/pizza/pizza_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>